owner: XsopGroup
repo: status

sites:
  - name: 秀操作
    url: https://www.xsop.de
  - name: IPShow
    url: https://ipshow.de
  - name: Cloudfare Bond
    url: https://cloudfare.bond
  - name: BestIP
    url: https://bestip.bond
  - name: 127001 Bond
    url: https://127001.bond
